### ISSUE TITLE
Allow for the progress tracker to skip certain categories

### ISSUE THREAD

**Issue by laurensWe** [MinBZK/ai-act-decisiontree#151]
### Use Cases

When following the steps in the decision tree, if could be that certain categories are completely skipped based on the answers, right now that means that the progress tracker would be in the "incomplete" state, if they are completely skipped it would be better if they get the "disabled" state. Right now as a certain hierarchy is missing in the categories, it is hard to find when a step is skipped and also when reverting the questions how to unskip them. A new datamodel would be needed for the categories for this.

### Proposal

Rewrite the categories datamodel to allow for skipping of categories and also implement this skipping state for the progress tracker

**Comment by ravimeijerrig** [comment]
Not relevant anymore
