### ISSUE TITLE
Werkt niet in Safari 18.0

### ISSUE THREAD

**Issue by FrieseWoudloper** [MinBZK/ai-act-decisiontree#154]
### Expected Behavior

De vraag, toelichting en antwoorden zouden weergegeven moeten worden.

### Actual Behavior

De beslisboom werkt bij mij niet in Safari 18.0. Ik zie alleen de voortgang die normaliter links in het scherm getoond wordt. Niet de tekst, vragen en antwoorden die bij het onderdeel horen waar ik op dat moment ben.
Ik krijg ook geen melding dat de beslisboom niet geschikt is voor mijn browser.

**Comment by anneschuth** [comment]
@FrieseWoudloper Hoe ziet het er bij jou uit? Ik heb het net uitgeprobeerd op Safari 18.0 (20619.1.26.31.6), zie onderstaande screenshot: 
![image](https://github.com/user-attachments/assets/20047b80-a21c-43ed-9039-b438bafaf4c3)

**Comment by laurensWe** [comment]
Closing this ticket as it works for me and Willy on Safari 18.0 in the end, still very interesting bug :S
