### ISSUE TITLE
Deploy the ai-act-beslisboom as a package to github instead of NPM

### ISSUE THREAD

**Issue by anneschuth** [MinBZK/ai-act-decisiontree#192]
## Description
When you release the ai-act-beslisboom then an NPM package will be built, we could move this to be an GitHub package.  So on release you can get the packages at the [release page of Github](https://github.com/MinBZK/ai-act-decisiontree/releases). How the package is shown should be changed in the gh action like [this](https://github.com/softprops/action-gh-release?tab=readme-ov-file#%EF%B8%8F-uploading-release-assets).

## Technical Implementation
- [x] Change the Github Action to output files which are directly importable by the html of Algoritmekader
- [x] Get access token approval from BZK (is requested)
- [x] Remove deployment at https://www.npmjs.com/package/ai-act-decision-tree
- [x] Remove code that does the npm deployment
- [ ] Refactor the Algoritmekader implementation of this https://github.com/MinBZK/Algoritmekader/pull/251

**Comment by laurensWe** [comment]
Current status: Waiting for Boris to approve of the PAT for this github action to edit the releases
