### ISSUE TITLE
Vraag 1.0 opsplitsen

### ISSUE THREAD

**Issue by FrieseWoudloper** [MinBZK/ai-act-decisiontree#24]
### Use Cases

Vraag 1.0 is lang en ingewikkeld. Volgens mij kan hij beter opgesplitst worden.

### Proposal

Ik zou sowieso de vraag 'Is het een AI systeem onder de AIA?' splitsen van 'Is het een GPAI systeem onder de AIA?'. Een GPAI is ook een AI, maar niet alle AI is GPAI. Dus het lijkt me logisch en overzichtelijker om voor GPAI een vervolgvraag te maken.

Ook zou ik het GPAI noemen en niet 'AI systeem voor algemene doeleinden'. Ten eerste is het te lang en maakt het de tekst nodeloos ingewikkeld, ten tweede zegt in de praktijk iedereen GPAI. Ik moest echt nadenken over wat er bedoeld werd met 'AI systeem voor algemene doeleinden'.

Wat is de doelgroep? Als het niet per se juristen zijn, dan zou ik in de beslisboom verwijzen naar de definitie voor AI systeem in de AIA, maar in de beslisboom zelf geen lange, juridische formuleringen gebruiken. Om te toetsen of iets onder de definitie van AI systeem valt, kun je het opsplitsen in eenvoudiger vragen:
- Is het systeem een computerprogramma of software, in plaats van een handmatig of mechanisch systeem?
- Opereert het systeem tot op zekere hoogte onafhankelijk, of heeft het continu menselijk toezicht nodig?
- Kan het systeem leren en zijn gedrag aanpassen op basis van nieuwe gegevens of ervaringen?
- Analyseert het systeem gegevens om output te genereren die van invloed kunnen zijn op de fysieke of virtuele omgeving?

**Comment by laurensWe** [comment]
Hi Willy,
