### ISSUE TITLE
Zinsnede in 5.24.0.0 en 5.24.0.2 verwijderen

### ISSUE THREAD

**Issue by FrieseWoudloper** [MinBZK/ai-act-decisiontree#27]
### Use Cases

In vraag 5.24.0.0 en 5.24.0.2 staat '... bevat het systeem geen significant risico op schade voor de gezondheid, veiligheid of de grondrechten van natuurlijke personen?'. Volgens mij moet dat weg. Vragen 5.24.0.0 tot en met 5.24.0.4 zijn volgens mij juist bedoeld om helder te maken wanneer geen sprake is van significant risico op schade voor de gezondheid, veiligheid of grondrechten van natuurlijke personen. Door die zinsnede toe te voegen, maak je het weer onzeker.

### Proposal

Zinsnede in beide vragen weghalen.

**Comment by laurensWe** [comment]
De structuur rondom publicatiecategorie hoog-risico AI is aangepast. Zie vraag 5.0 (hoog-risico AI) , 5.1.0 (uitzondering hoog-risico AI) en 5.1 (profilering).
