### ISSUE TITLE
Annex III systeem dat natuurlijke personen profileert is altijd hoog risico

### ISSUE THREAD

**Issue by FrieseWoudloper** [MinBZK/ai-act-decisiontree#28]
### Use Cases

Een Annex III systeem dat natuurlijke personen profileert is altijd hoog risico. Dat krijg ik nu niet uit de beslisboom. Zie vraag 5.24.0.0.1. 
Als het antwoord op 5.24.0.0.1 'Ja' is, hoef je vragen 5.24.0.0, 5.24.0.2, 5.24.0.3 en 5.24.0.4 niet meer te stellen.

### Proposal

Vraag 5.24.0.0.1 naar voren halen. Als het antwoord 'Ja' is, het AI systeem classificeren als 'Hoog risico'.

**Comment by laurensWe** [comment]
De structuur rondom publicatiecategorie hoog-risico AI is aangepast. Zie vraag 5.0 (hoog-risico AI) , 5.1.0 (uitzondering hoog-risico AI) en 5.1 (profilering).
