### ISSUE TITLE
Hoog risico + transparantie verplichtingen

### ISSUE THREAD

**Issue by FrieseWoudloper** [MinBZK/ai-act-decisiontree#29]
### Use Cases

Ik heb een vraag:
Ik heb begrepen dat de transparantieverplichtingen voor limited risk ook van toepassingen kunnen zijn op hoog risico algoritmen. Houdt deze beslisboom daar ook rekening mee?

**Comment by laurensWe** [comment]
Limited risk is geen officiële term volgens de AIA. Limited risk en Minimal Risk worden nu beide samengevoegd onder ‘geen hoog-risico AI’.

Als je een AI-systeem of AI-systeem voor algemene doeleinden bent kom je langs transparantieverplichting (ongeacht of je hoog of laag risico bent).
