### ISSUE TITLE
Test case voor beslisboom

### ISSUE THREAD

**Issue by FrieseWoudloper** [MinBZK/ai-act-decisiontree#30]
### Use Cases

Ik heb geprobeerd om voor een test case de beslisboom te doorlopen, maar dat ging niet goed. Ik deel hier de case, omdat het jullie misschien kan helpen bij het testen. Het lijkt me goed om meer cases zoals deze op te stellen.

==========================

Risicoprofilering voor heronderzoek van bijstandsuitkeringen van de gemeente Rotterdam

Context 

De casus betreft een AI-systeem van de gemeente Rotterdam voor het selecteren van bijstandsontvangers voor heronderzoek. Het AI model is door de gemeente Rotterdam in samenwerking met een bedrijf ontworpen en gebouwd.  Het systeem is van 2017 tot en met 2021 in gebruik geweest. 

30.000 inwoners van Rotterdam ontvangen een bijstandsuitkering. De gemeente heeft de wettelijke taak om te controleren of deze uitkeringen rechtmatig worden verstrekt, maar de heeft te weinig capaciteit om dat jaarlijks voor alle bijstandsontvangers te doen. Rotterdam wil de beperkte capaciteit zo efficiënt mogelijk inzetten en zo veel mogelijk onrechtmatige uitkeringen opsporen. Voor dit doel maakt de gemeente gebruik van een AI systeem. 

Na een kritisch rapport van de Rekenkamer is de gemeente voorlopig met het AI systeem gestopt. De gemeente buigt zich nu over het herontwerp van het systeem. Daarbij moet de gemeente ook rekening houden met de risicoclassificatie onder de AI Act. De risicoclassificatie kan namelijk bepalen dat het AI systeem verboden is of dat er specifieke eisen aan worden gesteld.

Inputs

Het model is getraind op een dataset met ruim tienduizend heronderzoeken van Rotterdam uit het verleden.  De dataset bevat meer dan vijftig kenmerken van een inwoner, waaronder geslacht, leeftijd, postcode, huwelijkse staat, aantal kinderen, beheersing van de Nederlandse taal, assertiviteit, professioneel voorkomen, bezoek aan psycholoog en bijstandsrelatie is onrechtmatig.

Output

Het gaat om een machine learning model dat getraind is met het xgboost algoritme. Het model voorspelt de kans dat een inwoner onrechtmatig bijstand ontvangt. Het model is een selectiefilter. Als de voorspelde kans boven een bepaalde drempelwaarde ligt, wordt de betreffende bijstandsontvanger door het AI systeem geselecteerd. 

Actie

Bijstandsontvangers die door het AI systeem zijn geselecteerd, worden door de gemeente onderworpen aan een heronderzoek. Ze moeten aanvullende informatie aanleveren, zoals inkomensgegevens, bankafschriften of andere relevante documenten. Een huisbezoek kan ook onderdeel zijn van het onderzoek. Betrokkenen ervaren dit vaak als indringend, stressvol en stigmatiserend. 

Wanneer de gemeente concludeert dat er inderdaad sprake is van een onrechtmatige bijstandsuitkering, legt zij maatregelen op. De uitkering wordt aangepast, stopgezet of teruggevorderd. De gemeente kan ook een boete opleggen.

Classificatie van het algoritme:
- De gemeente Rotterdam (een Europese overheidsinstantie) is zowel provider als deployer van het systeem, en de output van het systeem wordt gebruikt om te bepalen of inwoners van Rotterdam (en dus inwoners van de EU) aan een heronderzoek worden onderworpen. Daarmee is het systeem in scope van de AIA. 
- De basis van het systeem is een machine learning model. Het gaat om software die tot op bepaalde hoogte onafhankelijk opereert en kan leren van nieuwe data. De output van het systeem heeft consequenties voor inwoners. De output beïnvloedt dus de fysieke omgeving. Daarmee voldoet het aan de definitie van een AI systeem in de AIA. 
- Het AI systeem is ontwikkeld voor het uitvoeren van één gespecialiseerde taak. Het is geen General Purpose AI. 
- Het AI systeem betreft geen R&D of wetenschappelijk onderzoek, het is geen open-source en het AI systeem wordt ook niet uitsluitend gebruikt voor militaire doeleinden, defensie of nationale veiligheid. Daarmee valt het systeem niet onder de uitzonderingen van de AIA. 
- The AI system is not listed in Article 5, Prohibited AI Practices. Het is onder de AIA niet verboden om een AI systeem te ontwikkelen en te gebruiken voor profilering van personen voor heronderzoek naar onrechtmatig verstrekte bijstandsuitkeringen. Het gaat hier dus niet om een verboden systeem.
- The AI system is not covered by the Union harmonization legislation listed in Annex I.
- The AI system is listed in Annex III para. 5 lit a: ‘’AI systems intended to be used by public authorities or on behalf of public authorities to evaluate the eligibility of natural persons for essential public assistance benefits and services, including healthcare services, as well as to grant, reduce, revoke, or reclaim such benefits and services;’
- The AI system performs profiling of natural persons and in doing so, poses a significant risk of harm to the health, safety or fundamental rights of natural persons.
- Conclusion: Rotterdam’s system is a high risk AI system.

**Comment by laurensWe** [comment]
Het is inderdaad een goed idee om met test-cases te gaan werken.
@ravimeijerrig heeft met de casus door de beslisboom gelopen en ben tot de volgende resultaten gekomen: 
![image](https://github.com/user-attachments/assets/1665102e-2b93-469a-9046-7de83d3988b7)
![image](https://github.com/user-attachments/assets/a19f267a-801b-4b9a-8a9d-4b1ac35d79c7)

Heb je nog meer use cases? En ik zou zeggen nu de boom in een mooie staat is, deel het vooral binnen jouw kringen en kijken of mensen hier direct al feedback op hebben, dan zie ik de feedback graag tegemoet als een nieuw issue zodat we het niet uit het oof verliezen en kunnen verwerken.
