### ISSUE TITLE
Switch from Vue to React

### ISSUE THREAD

**Issue by anneschuth** [MinBZK/ai-act-decisiontree#72]
## Description
We want to align with NL design system and therefore need to refactor from Vue to React. 
Utrecht has Vue components, but in their own 'style'. 

## Implementation
- Redo code that lives here: https://github.com/MinBZK/ai-act-decisiontree/tree/main/frontend

**Comment by laurensWe** [comment]
No need, as the NL Design system currently it flexible enough to support us
